apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g5ov2u93i-nodejs
  janus-idp.io/tekton: g5ov2u93i-nodejs
  backstage.io/kubernetes-id: g5ov2u93i-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g5ov2u93i-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
