apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g5ov2u93i-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g5ov2u93i-nodejs 
  name: g5ov2u93i-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g5ov2u93i-nodejs 
